baseurl = "https://blog.tomasino.org"
title = "Tomasino Blog"
languageCode = "en-us"
theme = "blank"
MetaDataFormat = "yaml"
pygmentsCodeFences = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
[params]
    author = "James Tomasino"
    description = "Personal blog of James Tomasino"
[author]
    name = "James Tomasino"
