baseurl = "https://blog.tomasino.org"
title = "Tomasino Blog"
languageCode = "en-us"
theme = "blank"
MetaDataFormat = "yaml"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
[author]
    name = "James Tomasino"
